name: setup
description: Run setup
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install packages
      uses: borales/actions-yarn@v4
      with:
        cmd: install
