name: setup
description: Run setup
runs:
  steps:
    # Will want to template these steps separately at some point. 
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install packages
      uses: borales/actions-yarn@v4
      with:
        cmd: install
