on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  security:
    name: Run Quality Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk monitor
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
