on:
  - pull_request

# Once all the commands pass, these can be made
# to run sequentially and block merges.

jobs:
  lint:
    uses: ./.github/workflows/quality-check.yml
    name: Lint
    with:
      cmd: lint --max-warnings=0

  type-check:
    uses: ./.github/workflows/quality-check.yml
    name: Type Check
    with:
      cmd: type-check

  unit-tests:
    uses: ./.github/workflows/quality-check.yml
    name: Run unit tests
    with:
      cmd: test
