on:
  - pull_request

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-22.04
    needs: [lint, type-check, unit-tests]
    steps:
      - run: |
          echo Checks complete!

  lint:
    uses: ./.github/workflows/quality-check.yml
    with:
      cmd: lint --max-warnings=0
      name: Lint

  type-check:
    uses: ./.github/workflows/quality-check.yml
    with:
      cmd: type-check
      name: Type Check

  unit-tests:
    uses: ./.github/workflows/quality-check.yml
    with:
      cmd: test
      name: Run unit tests
