on:
  pull_request:
    types: [opened, synchronize]

jobs:
  quality_checks:
    name: Run Quality Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run the unit tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command
