on:
  pull_request:
    types: [opened, edited]

jobs:
  quality_checks:
    name: Run Quality Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Echo
        run: |
          echo 'This command only outputs this message.'
